<!DOCTYPE html>
<html class="bg-primary" style="box-sizing: border-box; --bs-blue: #0d6efd; --bs-indigo: #6610f2; --bs-purple: #6f42c1; --bs-pink: #d63384; --bs-red: #dc3545; --bs-orange: #fd7e14; --bs-yellow: #ffc107; --bs-green: #198754; --bs-teal: #20c997; --bs-cyan: #0dcaf0; --bs-white: #fff; --bs-gray: #6c757d; --bs-gray-dark: #343a40; --bs-primary: #0d6efd; --bs-secondary: #6c757d; --bs-success: #198754; --bs-info: #0dcaf0; --bs-warning: #ffc107; --bs-danger: #dc3545; --bs-light: #f8f9fa; --bs-dark: #212529; --bs-font-sans-serif: system-ui,-apple-system,'Segoe UI',Roboto,'Helvetica Neue',Arial,'Noto Sans','Liberation Sans',sans-serif,'Apple Color Emoji','Segoe UI Emoji','Segoe UI Symbol','Noto Color Emoji'; --bs-font-monospace: SFMono-Regular,Menlo,Monaco,Consolas,'Liberation Mono','Courier New',monospace; --bs-gradient: linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0)); background-color: #0d6efd;">
<head>
    <title>You Are Invited To Join Smart School</title>
</head>
<body class="bg-primary container pt-5" style="box-sizing: border-box; margin: 0; font-family: var(--bs-font-sans-serif); font-size: 1rem; font-weight: 400; line-height: 1.5; color: #212529; -webkit-text-size-adjust: 100%; -webkit-tap-highlight-color: transparent; width: 100%; padding-right: var(--bs-gutter-x,.75rem); padding-left: var(--bs-gutter-x,.75rem); margin-right: auto; margin-left: auto; padding-top: 3rem; background-color: #0d6efd;">
    <div class="row" style="box-sizing: border-box; --bs-gutter-x: 1.5rem; --bs-gutter-y: 0; display: flex; flex-wrap: wrap; margin-top: calc(var(--bs-gutter-y) * -1); margin-right: calc(var(--bs-gutter-x) * -.5); margin-left: calc(var(--bs-gutter-x) * -.5);">
        <div class="card col-10 col-md-8 mx-auto p-4 p-md-5" style="box-sizing: border-box; flex-shrink: 0; max-width: 100%; padding-right: calc(var(--bs-gutter-x) * .5); padding-left: calc(var(--bs-gutter-x) * .5); margin-top: var(--bs-gutter-y); flex: 0 0 auto; width: 83.33333333%; position: relative; display: flex; flex-direction: column; min-width: 0; word-wrap: break-word; background-color: #fff; background-clip: border-box; border: 1px solid rgba(0,0,0,.125); border-radius: .25rem; margin-right: auto; margin-left: auto; padding: 1.5rem;">
            <h1 style="box-sizing: border-box; margin-top: 0; margin-bottom: .5rem; font-weight: 500; line-height: 1.2; font-size: calc(1.375rem + 1.5vw);">You Are Invited To Join Smart School</h1>
            <div class="card-body" style="box-sizing: border-box; flex: 1 1 auto; padding: 1rem 1rem;">
                <p style="box-sizing: border-box; margin-top: 0; margin-bottom: 1rem;">Hi <b style="box-sizing: border-box; font-weight: bolder;">{{ $details['name'] }}</b>, you have been added as a member of <b style="box-sizing: border-box; font-weight: bolder;">{{ $details['school'][0]['name'] }}</b> by your school administrator.<br style="box-sizing: border-box;">To login to your account, please use this login info.</p>
                <table class="table" style="box-sizing: border-box; caption-side: bottom; border-collapse: collapse; --bs-table-bg: transparent; --bs-table-accent-bg: transparent; --bs-table-striped-color: #212529; --bs-table-striped-bg: rgba(0, 0, 0, 0.05); --bs-table-active-color: #212529; --bs-table-active-bg: rgba(0, 0, 0, 0.1); --bs-table-hover-color: #212529; --bs-table-hover-bg: rgba(0, 0, 0, 0.075); width: 100%; margin-bottom: 1rem; color: #212529; vertical-align: top; border-color: #dee2e6;" width="100%" valign="top">
                    <tr style="box-sizing: border-box; border-color: inherit; border-style: solid; border-width: 0;"><th style="box-sizing: border-box; text-align: inherit; text-align: -webkit-match-parent; border-color: inherit; border-style: solid; border-width: 0;" align="-webkit-match-parent">Role</th><td style="box-sizing: border-box; border-color: inherit; border-style: solid; border-width: 0;">{{ $details['role'] == 3 ? 'Student' : 'Teacher' }}</td></tr>
                    <tr style="box-sizing: border-box; border-color: inherit; border-style: solid; border-width: 0;"><th style="box-sizing: border-box; text-align: inherit; text-align: -webkit-match-parent; border-color: inherit; border-style: solid; border-width: 0;" align="-webkit-match-parent">Email Address</th><td style="box-sizing: border-box; border-color: inherit; border-style: solid; border-width: 0;">{{ $details['email'] }}</td></tr>
                    <tr style="box-sizing: border-box; border-color: inherit; border-style: solid; border-width: 0;"><th style="box-sizing: border-box; text-align: inherit; text-align: -webkit-match-parent; border-color: inherit; border-style: solid; border-width: 0;" align="-webkit-match-parent">Password</th><td style="box-sizing: border-box; border-color: inherit; border-style: solid; border-width: 0;">{{ $details['password'] }}</td></tr>
                </table>
                <p class="pt-3" style="box-sizing: border-box; margin-top: 0; margin-bottom: 1rem; padding-top: 1rem;">Best regards,<br style="box-sizing: border-box;">Smart School Team</p>
            </div>
        </div>
    </div>
</body>
</html>
